"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.flows_api import FlowsApi  # noqa: E501


class TestFlowsApi(unittest.TestCase):
    """FlowsApi unit test stubs"""

    def setUp(self):
        self.api = FlowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_all_flows_delete(self):
        """Test case for clear_all_flows_delete

        Terminate all running Flows  # noqa: E501
        """
        pass

    def test_create_flows_post(self):
        """Test case for create_flows_post

        Create a Flow from a YAML config  # noqa: E501
        """
        pass

    def test_delete_flows_id_delete(self):
        """Test case for delete_flows_id_delete

        Terminate a running Flow  # noqa: E501
        """
        pass

    def test_fetch_flow_params_flows_arguments_get(self):
        """Test case for fetch_flow_params_flows_arguments_get

        Get all accept arguments of a Flow  # noqa: E501
        """
        pass

    def test_get_items_flows_get(self):
        """Test case for get_items_flows_get

        Get all alive Flows' status  # noqa: E501
        """
        pass

    def test_status_flows_id_get(self):
        """Test case for status_flows_id_get

        Get the status of a running Flow  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
