"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.logs_api import LogsApi  # noqa: E501


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_logs_logs_workspace_id_log_id_get(self):
        """Test case for export_logs_logs_workspace_id_log_id_get

         Export Logs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
