"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.daemon_api import DaemonApi  # noqa: E501


class TestDaemonApi(unittest.TestCase):
    """DaemonApi unit test stubs"""

    def setUp(self):
        self.api = DaemonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_home_get(self):
        """Test case for home_get

         Home  # noqa: E501
        """
        pass

    def test_status_status_get(self):
        """Test case for status_status_get

        Get the status of the daemon  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
