"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.flow_item_status import FlowItemStatus
globals()['FlowItemStatus'] = FlowItemStatus
from openapi_client.model.flow_store_status import FlowStoreStatus


class TestFlowStoreStatus(unittest.TestCase):
    """FlowStoreStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowStoreStatus(self):
        """Test FlowStoreStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FlowStoreStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
