"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.peas_api import PeasApi  # noqa: E501


class TestPeasApi(unittest.TestCase):
    """PeasApi unit test stubs"""

    def setUp(self):
        self.api = PeasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_all_peas_delete(self):
        """Test case for clear_all_peas_delete

        Terminate all running Peas  # noqa: E501
        """
        pass

    def test_create_peas_post(self):
        """Test case for create_peas_post

        Create a Pea  # noqa: E501
        """
        pass

    def test_delete_peas_id_delete(self):
        """Test case for delete_peas_id_delete

        Terminate a running Pea  # noqa: E501
        """
        pass

    def test_fetch_pea_params_peas_arguments_get(self):
        """Test case for fetch_pea_params_peas_arguments_get

        Get all accept arguments of a Pea  # noqa: E501
        """
        pass

    def test_get_items_peas_get(self):
        """Test case for get_items_peas_get

        Get all alive Pea' status  # noqa: E501
        """
        pass

    def test_status_peas_id_get(self):
        """Test case for status_peas_id_get

        Get status of a running Pea  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
