"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.pods_api import PodsApi  # noqa: E501


class TestPodsApi(unittest.TestCase):
    """PodsApi unit test stubs"""

    def setUp(self):
        self.api = PodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_all_pods_delete(self):
        """Test case for clear_all_pods_delete

        Terminate all running Pods  # noqa: E501
        """
        pass

    def test_create_pods_post(self):
        """Test case for create_pods_post

        Create a Pod  # noqa: E501
        """
        pass

    def test_delete_pods_id_delete(self):
        """Test case for delete_pods_id_delete

        Terminate a running Pod  # noqa: E501
        """
        pass

    def test_fetch_pod_params_pods_arguments_get(self):
        """Test case for fetch_pod_params_pods_arguments_get

        Get all accept arguments of a Pod  # noqa: E501
        """
        pass

    def test_get_items_pods_get(self):
        """Test case for get_items_pods_get

        Get all alive Pods' status  # noqa: E501
        """
        pass

    def test_status_pods_id_get(self):
        """Test case for status_pods_id_get

        Get status of a running Pod  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
