"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.store_item_status import StoreItemStatus
globals()['StoreItemStatus'] = StoreItemStatus
from openapi_client.model.store_status import StoreStatus


class TestStoreStatus(unittest.TestCase):
    """StoreStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreStatus(self):
        """Test StoreStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoreStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
