"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.store_item_status import StoreItemStatus


class TestStoreItemStatus(unittest.TestCase):
    """StoreItemStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreItemStatus(self):
        """Test StoreItemStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StoreItemStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
