"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.flow_item_status import FlowItemStatus


class TestFlowItemStatus(unittest.TestCase):
    """FlowItemStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowItemStatus(self):
        """Test FlowItemStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FlowItemStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
