"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.flow_store_status import FlowStoreStatus
from openapi_client.model.store_status import StoreStatus
globals()['FlowStoreStatus'] = FlowStoreStatus
globals()['StoreStatus'] = StoreStatus
from openapi_client.model.daemon_status import DaemonStatus


class TestDaemonStatus(unittest.TestCase):
    """DaemonStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDaemonStatus(self):
        """Test DaemonStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DaemonStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
