"""
    JinaD (Daemon)

    REST interface for managing distributed Jina  # noqa: E501

    The version of the OpenAPI document: 0.9.32
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pod_model import PodModel


class TestPodModel(unittest.TestCase):
    """PodModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPodModel(self):
        """Test PodModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PodModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
