/**
 * JinaD (Daemon)
 * REST interface for managing distributed Jina
 *
 * The version of the OpenAPI document: 0.9.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowStoreStatus } from './flowStoreStatus';
import { StoreStatus } from './storeStatus';

export class DaemonStatus {
    'jina': object;
    'envs': object;
    'peas': StoreStatus;
    'pods': StoreStatus;
    'flows': FlowStoreStatus;
    'workspaces': StoreStatus;
    'usedMemory': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jina",
            "baseName": "jina",
            "type": "object"
        },
        {
            "name": "envs",
            "baseName": "envs",
            "type": "object"
        },
        {
            "name": "peas",
            "baseName": "peas",
            "type": "StoreStatus"
        },
        {
            "name": "pods",
            "baseName": "pods",
            "type": "StoreStatus"
        },
        {
            "name": "flows",
            "baseName": "flows",
            "type": "FlowStoreStatus"
        },
        {
            "name": "workspaces",
            "baseName": "workspaces",
            "type": "StoreStatus"
        },
        {
            "name": "usedMemory",
            "baseName": "used_memory",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DaemonStatus.attributeTypeMap;
    }
}

