/**
 * JinaD (Daemon)
 * REST interface for managing distributed Jina
 *
 * The version of the OpenAPI document: 0.9.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StoreItemStatus {
    'timeCreated': Date;
    'arguments': object | Array<any>;
    'workspaceId': string;
    'workdir': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timeCreated",
            "baseName": "time_created",
            "type": "Date"
        },
        {
            "name": "arguments",
            "baseName": "arguments",
            "type": "object | Array<any>"
        },
        {
            "name": "workspaceId",
            "baseName": "workspace_id",
            "type": "string"
        },
        {
            "name": "workdir",
            "baseName": "workdir",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StoreItemStatus.attributeTypeMap;
    }
}

